on:
  push:
    branches:
      - main
jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.x'
      - run: node scripts/conduct-census.js
      - run: node scripts/merge-aliases.js
      - run: node scripts/create-leaderboard.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - run: |
          git diff --quiet && echo "no changes" && exit
          git config user.name "Consensus Bot"
          git config user.email tienlen@example.org
          git add .
          git commit -m "consensus"
          git push
